title: "Event Store Documentation"
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

top_level_sections:
    - Introduction
    - Server
    - .NET API
    - HTTP API

latest_versions:
    server: 3.5.0
    dotnet-api: 3.5.0
    http-api: 3.5.0

defaults:
    -
        scope:
            path: ""
        values:
            exclude_from_sidebar: false
            layout: "docs"
            pinned: false
