title: "Event Store Documentation"
permalink: pretty
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

highlighter: pygments

top_level_sections:
    - Introduction
    - Server
    - .NET API
    - HTTP API
    - CLI

latest_versions:
    server: 3.8.0
    dotnet-api: 3.8.0
    http-api: 3.8.0
    introduction: 3.8.0
    cli: 1.1.0

all_versions:
    - 3.8.0
    - 3.7.0
    - 3.6.0
    - 3.5.0
    - 3.4.0
    - 3.3.0
    - 3.2.0
    - 3.1.0
    - 3.0.5
    - 3.0.3
    - 3.0.2
    - 3.0.1
    - 3.0.0

all_cli_versions:
    - 1.1.0
    - 1.0.0

defaults:
    -
        scope:
            path: ""
        values:
            exclude_from_sidebar: false
            layout: "docs"
            pinned: false
